### ISSUE TITLE
Can't build on Rust v1.65 -- told to re-compile single dependency in Rust v1.60??

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/libc#3198]
(TL;DR in the end)

So yesterday I updated my packages in my OS's repo and get Rust to update from 1.60 to 1.65. I'm on a generally considered fast-paced OS so I guess 1.65 must be new right? (It's only 5 months old, so that's kinda really new.)

Then I try to build a Rust project I'm working on. It says libc uses unstable features. Less than 5 months old, really??

```
error[E0658]: `const extern fn` definitions are unstable
    --> /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.141/src/macros.rs:188:17
     |
188  | /                 pub $($constness)* unsafe extern fn $i($($arg: $argty),*
189  | |                 ) -> $ret {
190  | |                     $($body);*
191  | |                 }
     | |_________________^
     |
    ::: /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.141/src/unix/linux_like/mod.rs:1521:1
```
Anyway, I pin an old version of libc (can I please go back once more and say that **libc** is literally a library to interact with C which hasn't changed in years but the Rust lib needs a compiler that was created less than 5 months ago??), anyway, I pin the most recent version my dependencies require, 0.2.139, also fairly recent, but fair enough.

I try to compile again. Now I get this error..
```
error[E0514]: found crate `unicode_ident` compiled by an incompatible version of rustc
   --> /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.56/src/fallback.rs:780:17
    |
780 |     c == '_' || unicode_ident::is_xid_start(c)
    |                 ^^^^^^^^^^^^^
    |
    = help: please recompile that crate using this compiler (rustc 1.60.0) (consider running `cargo clean` first)
    = note: the following crate versions were found:
            crate `unicode_ident` compiled by rustc 1.65.0: /var/cargo-target/debug/deps/libunicode_ident-e9f5e90a9b71d552.rmeta
```

So Rust v1.65 is telling me that I should compile **a single crate** using an older version of Rust?? Wth even. And this is needed to compile **libc**??

How do I even recompile a single crate? And am I really supposed to go download or compile an old Rust version manually that my OS's repo doesn't provide? (No, rustup is not supported by my OS and is rustup really a toolchain dependency of **libc**??)

-----

</end rant>

The gist being, this is **libc**, it's a fundamental crate. Can you please either correctly use semver and publish major releases when breaking compilation or at the very least be more mindful about breaking compilation with older versions?

In our projects we always have an MSRV that is never newer than latest Debian, I think being able to compile a project on all of the major Linux distros should be a reasonable requirement, shouldn't it? The amount of times we had to pin libc specifically because of it or some of its dependencies violating semver is .. simply said, heartbreaking.

**Comment by stevenroose** [comment]
It turns out the latter problem of the double compilation was an OS issue, so I'll edit that away, the 1.65 build failure still stands though.

**Comment by JohnTitor** [comment]
Could you provide a reproducible example? I cannot reproduce your issue on my end (a simple code + 1.65).
And note that MSRV is quite essential to us, we provide support from Rust 1.13.0 to nightly and we've discussed the issue about the most reasonable MSRV [here](https://github.com/rust-lang/libs-team/issues/72).
