### ISSUE TITLE
CMSG_SPACE is no longer a const function

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#4115]
`CMSG_SPACE` is supposed to be a const function.  It was, until PR #4105.  Now, nix fails to build with the libc-0.2 branch.  It fails for both x86_64-unknown-linux-gnu and x86_64-unknown-freebsd.  I bisected the regression to verify that it really was #4105.

Steps to reproduce:
```
$ git clone git@github.com:nix-rust/nix.git
$ cd nix
$ sed -I "" 's!version = "0.2.164"!git = "https://github.com/rust-lang/libc.git", rev = "ae052d3b6a045d58b7ef3187a94de81695e2591e"!' Cargo.toml
$ cargo check --all-features
    Updating crates.io index
    Updating git repository `https://github.com/rust-lang/libc.git`
     Locking 54 packages to latest compatible versions
      Adding sysctl v0.4.6 (available: v0.6.0)
   Compiling autocfg v1.4.0
   Compiling libc v0.2.164 (https://github.com/rust-lang/libc.git?rev=ae052d3b6a045d58b7ef3187a94de81695e2591e#ae052d3b)
   Compiling cfg_aliases v0.2.1
    Checking cfg-if v1.0.0
    Checking pin-utils v0.1.0
    Checking bitflags v2.6.0
   Compiling nix v0.29.0 (/tmp/nix)
   Compiling memoffset v0.9.1
error[E0015]: cannot call non-const fn `CMSG_SPACE` in constant functions
   --> src/sys/socket/mod.rs:652:14
    |
652 |     unsafe { libc::CMSG_SPACE(mem::size_of::<T>() as libc::c_uint) as usize }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `nix` (lib) due to 1 previous error
```

**Comment by tgross35** [comment]
Thanks for catching this, I guess the `const-extern-fn` feature (that we need for `ctest`) isn't getting enabled. It should be on by default except for when `ctest` is looking at things.

**Comment by tgross35** [comment]
Fyi @SteveLauC this should be resolved

**Comment by tamird** [comment]
The current release (0.2.165) should be yanked. It is breaking downstream builds e.g. https://github.com/aya-rs/aya/actions/runs/12023826759/job/33518337160.

**Comment by SteveLauC** [comment]
> The current release (0.2.165) should be yanked. It is breaking downstream builds e.g. https://github.com/aya-rs/aya/actions/runs/12023826759/job/33518337160.

This issue was fixed in 0.2.165 🤔

**Comment by tamird** [comment]
> > The current release (0.2.165) should be yanked. It is breaking downstream builds e.g. https://github.com/aya-rs/aya/actions/runs/12023826759/job/33518337160.
> 
> This issue was fixed in 0.2.165 🤔

I don't think so. https://github.com/rust-lang/libc/commit/79afdcecbf3714dba466b3ced846d212b9271493 isn't contained in the 0.2.165 tag.

**Comment by tamird** [comment]
Looks like this is still an issue under miri in particular. I can reproduce it in [aya](github.com/aya-rs/aya):
```
tamird@Mac aya % cargo +nightly miri test --package aya --all-targets --target x86_64-unknown-linux-gnu --no-default-features --features async_std -- nothing-at-all
   Compiling rustix v0.38.41
error[E0015]: cannot call non-const fn `libc::CMSG_SPACE` in constant functions
   --> /Users/tamird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.41/src/net/send_recv/msg.rs:120:14
    |
120 |     unsafe { c::CMSG_SPACE(converted_len) as usize }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `rustix` (lib) due to 1 previous error

```

**Comment by tamird** [comment]
The problem is that this feature is on by default, which is not the same as it being on *always*. [`rustix` uses `default-features=false`](https://github.com/bytecodealliance/rustix/blob/ef39477129e2cffbef8928324cf7264a79018f5d/Cargo.toml#L41) which is the root cause of this breakage.

**Comment by tgross35** [comment]
The above was addressed in 0.2.166 https://github.com/rust-lang/libc/releases/tag/0.2.166
