### PR TITLE
Re-enable all roundtrip tests

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by semarie** [comment]
FYI, OpenBSD is failing with 2591005

**Comment by gnzlbg** [comment]
@semarie did you do a `cargo update` ? There was a ctest bug that was triggering some of these.

**Comment by semarie** [comment]
@gnzlbg no. I just built "as it is". isn't what CI do ?

**Comment by gnzlbg** [comment]
Did you check out a new repo? The libc dependencies are only updated when
you do a cargo update locally otherwise.

**Comment by semarie** [comment]
My build script did only a `git fetch` + `git reset --hard origin/master`. I changed it to do a checkout.

Now I am failing with:
```
Compiling libc-test v0.1.0
[...]
error[E0425]: cannot find value `mips64` in this scope
    --> libc-test/build.rs:2297:17
     |
2297 |             if (mips64 || sparc64) && gnu =>
     |                 ^^^^^^ help: a local variable with a similar name exists: `mips`

error[E0425]: cannot find value `s390x` in this scope
    --> libc-test/build.rs:2301:25
     |
2301 |         "mcontext_t" if s390x => true,
     |                         ^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `libc-test`.
```

Now, if I corrects the errors (in `test_linux()`) and remove `cfg.skip_roundtrip()` stuff from `test_openbsd()` it is still passing. So `cfg.skip_roundtrip()` isn't need anymore for OpenBSD.

**Comment by gnzlbg** [comment]
@semarie due to how cargo works, if you compile a clean checkout, dependencies are fetched, compiled, and your source code is compiled. If a new version of a dependency is released, it won't be re-downloaded until you either bump its requirements in the Cargo.toml, or you do a `cargo update`. 

> So cfg.skip_roundtrip() isn't need anymore for OpenBSD.

Thanks, I'll remove it here. Once this is green, I'll ping you to test this again before merging.

**Comment by gnzlbg** [comment]
@semarie everything is green. Before merging, could you check that this branch checks out cleanly and libc-test passes on openbsd ?

**Comment by semarie** [comment]
@gnzlbg it is fine on OpenBSD

**Comment by gnzlbg** [comment]
thanks for checking!
