### ISSUE TITLE
Version 0.2.63 breaks on musl

### ISSUE THREAD

**Issue by DianaNites** [rust-lang/libc#1483]
The latest update fails to compile when using musl targets. Minimum example.

```rust
use libc::ENETUNREACH;

fn main() {}
```

Fails with `cargo check --target=x86_64-unknown-linux-musl` on 0.2.63. Works on 0.2.62. Works on gnu targets.

Stable rust, 1.37.0

Seems to be for all errno constants? Thats whats failing at least.

```
error[E0425]: cannot find value `ENETUNREACH` in module `libc`
   --> /home/diana/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.15.0/src/errno.rs:682:33
    |
682 |         ENETUNREACH     = libc::ENETUNREACH,
    |                                 ^^^^^^^^^^^ not found in `libc`
help: possible candidate is found in another module, you can import it into scope
    |
578 |     use errno::consts::Errno::ENETUNREACH;
    |
```

**Comment by gnzlbg** [comment]
Thanks for the report.

**Comment by jbg** [comment]
Getting a similar compilation failure on musl here, but with `EINPROGRESS`.

```
   Compiling socket2 v0.3.11
error[E0425]: cannot find value `EINPROGRESS` in crate `libc`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.11/src/sys/unix.rs:141:58
    |
141 |             Err(ref e) if e.raw_os_error() == Some(libc::EINPROGRESS) => {}
    |                                                          ^^^^^^^^^^^ not found in `libc`
```

**Comment by gnzlbg** [comment]
Offending commit: https://github.com/rust-lang/libc/commit/9df2deb33bde1330c9a2e5120ca2e86ad2b5b1fd

This should have been caught by our semver tests, but we disabled them when migrating to Azure pipelines (cc @pietroalbini  - any updates on allowing tests to fail? That's what's blocking re-adding these tests).

**Comment by pietroalbini** [comment]
> any updates on allowing tests to fail? That's what's blocking re-adding these tests

You should be able to add `continueOnError` on a job. [Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job)

**Comment by gnzlbg** [comment]
PR with a fix #1484

**Comment by gnzlbg** [comment]
I've yanked 0.2.63, @DianaNites @jbg a cargo update should hopefully revert your projects back to 0.2.62 which doesn't have the issue. Can you confirm that that works?

**Comment by jbg** [comment]
Works here. Thanks!
