### ISSUE TITLE
libc-test do not pass on macOs Xcode 13.1

### ISSUE THREAD

**Issue by devnexen** [rust-lang/libc#2507]
`  cargo:warning=/Users/dcarlier/Contribs/libc/target/debug/build/libc-test-824b81608838ae56/out/main.c:34439:71: error: use of undeclared identifier 'TIOCREMOTE'
  cargo:warning=            static const unsigned  long __test_const_TIOCREMOTE_val = TIOCREMOTE;`

Warning, this is not libc's bug but most likely a Xcode's actual version. Confirmed in two different Monterey/Xcode 13.1 machines, a quick ioctl's C code confirms it, it does not compile with XCode's clang but just do fine with both gcc and clang from homebrew and libc test pass with the latter.

Writing it down here just in case someone else encounters the same situation.

**Comment by JohnTitor** [comment]
@devnexen Is it actually removed or is an additional include needed? I don't have macOS env and cannot test on my local...

**Comment by devnexen** [comment]
even trying a little C code and including proper headers it does not compile with XCode/clang 13.1 but fine with homebrew compilers.

**Comment by JohnTitor** [comment]
Uhm, so we could say it's just an XCode issue, I guess. I'm not sure if we need any additional action here, but I've skipped a test and the failure is removed now, closing. Thanks for checking it!
