### ISSUE TITLE
windows-msvc: localtime_s/gmtime_s are header-inline CRT functions, fail to link (LNK2019) on VS 18 / MSVC 14.5x

### ISSUE THREAD

**Issue by ianm199** [rust-lang/libc#5299]
## Summary

`libc::localtime_s` and `libc::gmtime_s` for Windows are declared as plain externs (no `link_name`), e.g. in `src/windows/mod.rs`:

```rust
pub fn localtime_s(tmDest: *mut tm, sourceTime: *const time_t) -> errno_t;
```

In the UCRT these names are `static __inline` header wrappers (in `time.h`) that forward to `_localtime64_s`/`_gmtime64_s`; only the underscore-prefixed variants are actual exports of ucrtbase / `api-ms-win-crt-time-l1-1-0`. Microsoft's docs state localtime_s is implemented as an inline function.

## Behavior change

Historically this linked anyway with VS 2022-era import libraries. With Visual Studio 18 toolchains (MSVC 14.50 / 14.51 — which GitHub's `windows-latest` image now ships), linking any program that calls `libc::localtime_s`/`gmtime_s` fails:

```
error LNK2019: unresolved external symbol localtime_s
error LNK2019: unresolved external symbol gmtime_s
```

Same code, same libc version, links fine on VS 2022 (14.4x) — the compat objects that used to satisfy these names appear to be gone from the newer import libs.

## Repro

On `x86_64-pc-windows-msvc` with a VS 18 toolchain:

```rust
fn main() {
    unsafe {
        let t: libc::time_t = 0;
        let mut tm: libc::tm = core::mem::zeroed();
        libc::localtime_s(&mut tm, &t);
    }
}
```

## Suggested fix

Declare them with the exported symbol names, matching what the header inline does (libc's Windows `time_t` is `i64`, so the 64-bit variants are the right targets):

```rust
#[link_name = "_localtime64_s"]
pub fn localtime_s(tmDest: *mut tm, sourceTime: *const time_t) -> errno_t;
#[link_name = "_gmtime64_s"]
pub fn gmtime_s(tmDest: *mut tm, sourceTime: *const time_t) -> errno_t;
```

Other UCRT declarations that exist only as header inlines may deserve the same audit.

## Downstream reports

- https://github.com/ianm199/omnilua/issues/308 (end users on VS 18 unable to `cargo install`; five releases of CI on VS 2022 runners linked fine)
- https://github.com/wowemulation-dev/rilua/issues/21

**Comment by tgross35** [comment]
Regressed in https://github.com/rust-lang/libc/commit/5bbfc84e14f54392e4c07737d7ba8523b590d03e, we'll work on a fix.

> [bug: Windows MSVC release build fails with unresolved libc symbols wowemulation-dev/rilua#21](https://github.com/wowemulation-dev/rilua/issues/21)

This was opened in February. Was it ever working before?

**Comment by ianm199** [comment]
> Was it ever working before?

Ran the matrix to answer this properly ([probe run](https://github.com/ianm199/omnilua/actions/runs/29846708046): VS 2022 17.14 / MSVC 14.44 and VS 2026 18.7 / MSVC 14.51, libc pinned per cell). Conclusion up front: **this is purely a libc version regression — 0.2.187 is the first bad release and it fails on every MSVC toolchain. The VS 18 attribution in my report was wrong.** Restoring the two link_names (the 0.2.186 declarations) is the whole fix; verified that binding links and returns correct results on both toolchains.

| pinned libc | symbols | VS 2022 / 14.44 | VS 18 / 14.51 |
|---|---|---|---|
| 0.2.186 | `localtime_s` + `gmtime_s` | links, correct output | links, correct output |
| 0.2.187 / 0.2.188 | `localtime_s` + `gmtime_s` | LNK2019 | LNK2019 |
| 0.2.186–188 | `time` / `ctime` / `difftime` | links | links |
| none — plain externs | `localtime_s` + `gmtime_s` | LNK2019 | LNK2019 |

**rilua: never worked, and it isn't evidence about libc.** They declare `localtime_s`/`gmtime_s` in [their own extern block](https://github.com/wowemulation-dev/rilua/blob/v0.1.8/src/platform.rs), and plain names for these two have never linked on any MSVC toolchain (last row). Same symptom, unrelated cause.

**libc: worked since #2407.** Breakage starts exactly at 0.2.187 (Jul 20), the first 0.2.x release carrying the 5bbfc84e backport. My "worked on VS 2022, fails on VS 18" observation was a timing artifact: our green CI was already on the VS 2026 image but had 0.2.186 in its lockfile, while end-user `cargo install` resolved fresh 0.2.187 the day after it shipped.

Why only two of the five de-link_named functions broke: dumpbin shows msvcrt.lib carries compat objects for plain `time`/`ctime`/`difftime`/`gmtime`/`localtime` in every toolset (14.29, 14.44, 14.51), but no `*_s` variants have ever existed there or in ucrt.lib (only `_localtime{32,64}_s`/`_gmtime{32,64}_s`). Nothing was removed in VS 18 — the compat objects my issue text hypothesized never existed.

**Comment by tgross35** [comment]
Released in https://github.com/rust-lang/libc/releases/tag/0.2.189
